# stelle_backend/models/common_models.py
from pydantic import BaseModel, EmailStr
from typing import List, Optional
from enum import Enum

# --- Chat/RAG Models ---
class GenerateRequest(BaseModel):
    user_id: str
    session_id: str
    prompt: str
    filenames: List[str] = []

class GenerateResponse(BaseModel):
    response: str

class ResearchQuery(BaseModel):
    text: str

class DeepSearchRequest(BaseModel):
    user_id: str
    session_id: str
    prompt: str
    filenames: List[str] = []

class NLPRequest(BaseModel):
    user_id: str
    session_id: str
    message: str
    filenames: List[str] = []

class RegenerateRequest(BaseModel):
    user_id: str
    session_id: str
    filenames: List[str] = []

# --- Auth/Subscription Models ---
class Subscription(BaseModel):
    user_id: str
    subscription: dict
    time_zone: str = "UTC"

class OTPRequest(BaseModel):
    email: EmailStr

class VerifyOTPRequest(BaseModel):
    email: EmailStr
    otp: str
    new_password: Optional[str] = None



# --- Content/Browse Models ---
class BrowseRequest(BaseModel):
    query: str

class BrowseResponse(BaseModel):
    result: str
    
# CRITICAL FIX: Adding the missing Prompt model used by content_routes.py
class Prompt(BaseModel):
    text: str

# --- Goal/Planning Models (Simplified) ---
class PlanWeekRequest(BaseModel):
    user_id: str

# --- AI Assist Models ---
class UserInput(BaseModel):
    query: str

class PostGenOptions(str, Enum):
    Text = "text"
    Photo = "photo"
    Video = "video"
    
    
# In models/common_models.py (Add this class)
class ScrapeRequest(BaseModel):
    query: str
    max_results: int = 1


# In stelle_backend/models/common_models.py

# ... (Auth/Subscription Models) ...

# --- ADD THIS NEW MODEL ---
class RegisterUserRequest(BaseModel):
    user_id: str = None # Optional/autogenerated if you don't use tokens for ID
    email: EmailStr
    password: str
    username: str
# Placeholder for complex goal/task models that were commented out (optional future use)
# class Task(BaseModel): ...
# class Goal(BaseModel): ...